# Generated by Django 5.2.6 on 2025-09-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
